name: Build firmware

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build firmware

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Docker with nRF Connect SDK
        uses: 'docker://ralexeev/sdk-nrf:latest'

      - name: ls 1
        run: |
          ls -al
      - name: pwd 1
        run: |
          pwd
      - name: Docker container list 1
        run: |
          docker container ps -a

      - name: West Build
        run: |
          'docker run -it ralexeev/sdk-nrf /bin/bash -c "source /workdir/ncs/zephyr/zephyr-env.sh"'

      - name: ls 2
        run: |
          ls -al
      - name: pwd 2
        run: |
          pwd
      - name: Docker container list 2
        run: |
          docker container ps -a

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "nrf52840dk_nrf52840_build"
          path: build/zephyr/
