name: Build firmware

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build firmware

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Docker with nRF Connect SDK
        uses: 'docker://ralexeev/sdk-nrf:latest'

      - name: ls
        run: |
          ls -al

      - name: pwd
        run: |
          pwd

      - name: Docker container list
        run: |
          docker container ps -a

      - name: West Build
        run: |
          docker run -it ralexeev/sdk-nrf /bin/bash -c 'source /workdir/ncs/zephyr/zephyr-env.sh && west build -b nrf52840dk_nrf52840'

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "nrf52840dk_nrf52840_build"
          path: build/zephyr/
