name: Build firmware

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ralexeev/sdk-nrf:latest
    name: Build firmware

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: West Build
        shell: bash
        run: |
          source /workdir/ncs/zephyr/zephyr-env.sh
          west build -b nrf52840dk_nrf52840

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "nrf52840dk_nrf52840_build"
          path: build/zephyr/
