name: Build firmware

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build firmware

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: West Source
        uses: 'docker://ralexeev/sdk-nrf:latest'
        with: 
          entrypoint: source 
          args: '/workdir/ncs/zephyr/zephyr-env.sh'
          shell: bash
      - name: West Build
        uses: 'docker://ralexeev/sdk-nrf:latest'
        with: 
          entrypoint: west 
          args: 'build -b nrf52840dk_nrf52840'
          shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "nrf52840dk_nrf52840_build"
          path: build/zephyr/
