name: Build firmware

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build firmware

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ls 1
        run: |
          ls -al

      - name: pwd 1
        run: |
          pwd

      - name: Docker container list 1
        run: |
          docker container ps -a

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: |
            sdk-nrf-app:latest

      - name: ls 2
        run: |
          ls -al

      - name: pwd 2
        run: |
          pwd

      - name: Docker container list 2
        run: |
          docker container ps -a

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "nrf52840dk_nrf52840_build"
          path: build/zephyr/
