name: Build firmware

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: West Build
        uses: 'docker://ralexeev/sdk-nrf:latest'
        id: west-build
        run: west build -b nrf52840dk_nrf52840
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "nrf52840dk_nrf52840_build"
          path: build/zephyr/
