name: Build firmware

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ralexeev/sdk-nrf:latest
    name: Build firmware

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ls
        run: |
          ls -al

      - name: pwd
        run: |
          pwd

      - name: ls all
        run: |
          ls -al /workdir
          ls -al /workdir/ncs
          ls -al /workdir/ncs/zephyr
